engines:
    coverage:
        enabled: false

exclude_paths:
    - go-proio/model/**
    - go-proio/proto/**
    - py-proio/proio/model/**
    - py-proio/proio/proto/**
    - py-proio/tests/**
    - java-proio/src/main/java/proio/model/**
    - java-proio/src/main/java/proio/Proto.java
