branches:
    only:
        - master

env:
    global:
        - PY_DOCS_REPO_REF: github.com/decibelcooper/py-proio-docs.git

stages:
    - test
    - name: doc
      if: type = push

matrix:
    include:
        - language: go
          go: 1.7.x
        - language: go
          go: 1.8.x
        - language: go
          go: 1.9.x
        - language: go
          go: master

        - language: python
          python: 2.7
          install: pip install --upgrade pytest ./py-proio
          script: pytest ./py-proio
        - language: python
          python: 3.6
          install: pip install --upgrade pytest ./py-proio
          script: pytest ./py-proio
        - language: python
          python: nightly
          install: pip install --upgrade pytest ./py-proio
          script: pytest ./py-proio

        - language: python
          stage: doc
          python: 3.6
          install: pip install --upgrade sphinx pkginfo ./py-proio
          script:
              - cd py-proio/docs
              - bash genAndDeploy.sh

    allow_failures:
        - go: master
        - python: nightly

    fast_finish: true
    sudo: false
