branches:
    only:
        - master

env:
    global:
        - PY_DOCS_REPO_REF: github.com/decibelcooper/py-proio-docs.git

stages:
    - test
    - name: doc
      if: type = push
    - "unsupported test"

matrix:
    include:
        - language: go
          stage: "test"
          go: 1.7.x
        - language: go
          go: 1.8.x
        - language: go
          go: 1.9.x
        - language: go
          stage: "unsupported test"
          go: master

        - language: python
          stage: "test"
          python: 2.7
          install: pip install --upgrade pytest ./py-proio
          script: pytest ./py-proio
        - language: python
          python: 3.6
          install: pip install --upgrade pytest ./py-proio
          script: pytest ./py-proio
        - language: python
          stage: "unsupported test"
          python: nightly
          install: pip install --upgrade pytest ./py-proio
          script: pytest ./py-proio

        - language: python
          stage: doc
          python: 3.6
          install: pip install --upgrade sphinx pkginfo
          script:
              - cd py-proio
              - python setup.py sdist
              - pip install --upgrade .
              - cd docs
              - bash genAndDeploy.sh

    allow_failures:
        - go: master
        - python: nightly

    fast_finish: true
    sudo: false
