branches:
    only:
        - master

stages:
    - test
    - name: doc
      if: type = push

matrix:
    include:
        - language: go
          go: 1.7.x
        - language: go
          go: 1.8.x
        - language: go
          go: 1.9.x
        - language: go
          go: master

        - language: python
          python: 2.7
          install: pip install --upgrade pytest ./py-proio
          script: pytest ./py-proio
        - language: python
          python: 3.6
          install: pip install --upgrade pytest ./py-proio
          script: pytest ./py-proio
        - language: python
          python: nightly
          install: pip install --upgrade pytest ./py-proio
          script: pytest ./py-proio

        - language: cpp
          env:
              - PROTOBUF_VERSION: v3.0.2
              - LZ4_VERSION: v1.7.3
          install:
              - git clone https://github.com/lz4/lz4.git
              - cd lz4
              - git checkout tags/$LZ4_VERSION
              - make -j2
              - make PREFIX=$HOME install
              - cd ../
              - git clone https://github.com/google/protobuf.git
              - cd protobuf
              - git checkout tags/$PROTOBUF_VERSION
              - bash autogen.sh
              - ./configure --prefix=$HOME
              - make -j2
              - make install
              - cd ../
          script:
              - mkdir cpp-proio/build
              - cd cpp-proio/build
              - cmake -DCMAKE_PREFIX_PATH=$HOME ../
              - make -j2
              - make test

        - language: python
          env:
              - PY_DOCS_REPO_REF: github.com/decibelcooper/py-proio-docs.git
          stage: doc
          install: pip install --upgrade sphinx pkginfo
          script:
              - cd py-proio
              - python setup.py sdist
              - pip install --upgrade .
              - cd docs
              - bash genAndDeploy.sh

    allow_failures:
        - go: master
        - python: nightly
    fast_finish: true
    sudo: false
