# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proio/model/mc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proio/model/mc.proto',
  package='proio.model.mc',
  syntax='proto2',
  serialized_pb=_b('\n\x14proio/model/mc.proto\x12\x0eproio.model.mc\"\x90\x01\n\x0cMCParameters\x12\x0e\n\x06number\x18\x01 \x01(\x04\x12\x11\n\tprocessid\x18\x02 \x01(\x05\x12\x0e\n\x06weight\x18\x03 \x01(\x01\x12$\n\x04imap\x18\x04 \x03(\x0b\x32\x16.proio.model.mc.MapInt\x12\'\n\x04\x64map\x18\x05 \x03(\x0b\x32\x19.proio.model.mc.MapDouble\"$\n\x06MapInt\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x03(\x11\"\'\n\tMapDouble\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x03(\x01\"\xc9\x01\n\x11Pythia8Parameters\x12\x12\n\nweight_sum\x18\x01 \x01(\x01\x12\x16\n\x0emerging_weight\x18\x02 \x01(\x01\x12\x0e\n\x06pt_hat\x18\x03 \x01(\x01\x12\x10\n\x08\x61lpha_em\x18\x04 \x01(\x01\x12\x0f\n\x07\x61lpha_s\x18\x05 \x01(\x01\x12\x13\n\x0bscale_q_fac\x18\x06 \x01(\x01\x12\x0e\n\x06weight\x18\x07 \x01(\x01\x12\n\n\x02x1\x18\x08 \x01(\x01\x12\n\n\x02x2\x18\t \x01(\x01\x12\x0b\n\x03id1\x18\n \x01(\x04\x12\x0b\n\x03id2\x18\x0b \x01(\x04\x42\x43\n\x0bproio.modelB\x02McZ0github.com/decibelcooper/proio/go-proio/model/mc')
)




_MCPARAMETERS = _descriptor.Descriptor(
  name='MCParameters',
  full_name='proio.model.mc.MCParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='proio.model.mc.MCParameters.number', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processid', full_name='proio.model.mc.MCParameters.processid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='proio.model.mc.MCParameters.weight', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imap', full_name='proio.model.mc.MCParameters.imap', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dmap', full_name='proio.model.mc.MCParameters.dmap', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=185,
)


_MAPINT = _descriptor.Descriptor(
  name='MapInt',
  full_name='proio.model.mc.MapInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proio.model.mc.MapInt.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proio.model.mc.MapInt.value', index=1,
      number=2, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=223,
)


_MAPDOUBLE = _descriptor.Descriptor(
  name='MapDouble',
  full_name='proio.model.mc.MapDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proio.model.mc.MapDouble.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proio.model.mc.MapDouble.value', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=264,
)


_PYTHIA8PARAMETERS = _descriptor.Descriptor(
  name='Pythia8Parameters',
  full_name='proio.model.mc.Pythia8Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight_sum', full_name='proio.model.mc.Pythia8Parameters.weight_sum', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merging_weight', full_name='proio.model.mc.Pythia8Parameters.merging_weight', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pt_hat', full_name='proio.model.mc.Pythia8Parameters.pt_hat', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha_em', full_name='proio.model.mc.Pythia8Parameters.alpha_em', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha_s', full_name='proio.model.mc.Pythia8Parameters.alpha_s', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale_q_fac', full_name='proio.model.mc.Pythia8Parameters.scale_q_fac', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='proio.model.mc.Pythia8Parameters.weight', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x1', full_name='proio.model.mc.Pythia8Parameters.x1', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x2', full_name='proio.model.mc.Pythia8Parameters.x2', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id1', full_name='proio.model.mc.Pythia8Parameters.id1', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id2', full_name='proio.model.mc.Pythia8Parameters.id2', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=468,
)

_MCPARAMETERS.fields_by_name['imap'].message_type = _MAPINT
_MCPARAMETERS.fields_by_name['dmap'].message_type = _MAPDOUBLE
DESCRIPTOR.message_types_by_name['MCParameters'] = _MCPARAMETERS
DESCRIPTOR.message_types_by_name['MapInt'] = _MAPINT
DESCRIPTOR.message_types_by_name['MapDouble'] = _MAPDOUBLE
DESCRIPTOR.message_types_by_name['Pythia8Parameters'] = _PYTHIA8PARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MCParameters = _reflection.GeneratedProtocolMessageType('MCParameters', (_message.Message,), dict(
  DESCRIPTOR = _MCPARAMETERS,
  __module__ = 'proio.model.mc_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.mc.MCParameters)
  ))
_sym_db.RegisterMessage(MCParameters)

MapInt = _reflection.GeneratedProtocolMessageType('MapInt', (_message.Message,), dict(
  DESCRIPTOR = _MAPINT,
  __module__ = 'proio.model.mc_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.mc.MapInt)
  ))
_sym_db.RegisterMessage(MapInt)

MapDouble = _reflection.GeneratedProtocolMessageType('MapDouble', (_message.Message,), dict(
  DESCRIPTOR = _MAPDOUBLE,
  __module__ = 'proio.model.mc_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.mc.MapDouble)
  ))
_sym_db.RegisterMessage(MapDouble)

Pythia8Parameters = _reflection.GeneratedProtocolMessageType('Pythia8Parameters', (_message.Message,), dict(
  DESCRIPTOR = _PYTHIA8PARAMETERS,
  __module__ = 'proio.model.mc_pb2'
  # @@protoc_insertion_point(class_scope:proio.model.mc.Pythia8Parameters)
  ))
_sym_db.RegisterMessage(Pythia8Parameters)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\013proio.modelB\002McZ0github.com/decibelcooper/proio/go-proio/model/mc'))
# @@protoc_insertion_point(module_scope)
